using '../main.bicep'

param environment = 'prod'
param location = 'swedencentral'
param nameSuffix = 'wattops-${environment}'
param keyVaultName = 'kv-${nameSuffix}'
param queueName = 'planed-commands'
param additionalAppSettings = {
  PLANNER_QUEUE_NAME: queueName
  PRICE_AREA: 'DK1'
  PRICE_STOP_EXPORT_THRESHOLD_DKK_KWH: '0.02'
  PRICE_START_EXPORT_THRESHOLD_DKK_KWH: '3.00'
  PRICE_START_IMPORT_THRESHOLD_DKK_KWH: '0.10'
  GRID_FIRST_MINUTES_AFTER_SUNRISE: '120'
  SOLAR_OUTPUT_EXPORT_THRESHOLD_KWH: '25'
  SOLAR_OUTPUT_IMPORT_THRESHOLD_KWH: '5'
  SOLAR_LATITUDE: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=solar-latitude)'
  SOLAR_LONGITUDE: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=solar-longitude)'
  SOLAR_PANEL_KWP: '6.0'
  SOLAR_PANEL_TILT: '30'
  SOLAR_PANEL_AZIMUTH: '177'
  SOLAR_PERFORMANCE_RATIO: '0.95'
  DRY_RUN: 'false'
  LOCAL_TIMEZONE: 'Europe/Copenhagen'
  GROWATT_DEVICE_SERIAL_NUMBER: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=growatt-device-serial-number)'
  GROWATT_API_KEY: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=growatt-api-key)'
  GROWATT_CHARGE_POWER_PERCENT: '50'
  GROWATT_DISCHARGE_POWER_PERCENT: '50'
  GROWATT_STOP_DISCHARGE_SOC_PERCENT: '30'
  GROWATT_STOP_CHARGE_SOC_PERCENT: '90'
  PVNODE_API_KEY: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=pvnode-api-key)'
  PVNODE_SITE_ID: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=pvnode-site-id)'
  SOLCAST_RESOURCE_ID: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=solcast-resource-id)'
  SOLCAST_API_KEY: '@Microsoft.KeyVault(VaultName=${keyVaultName};SecretName=solcast-api-key)'
}
